# Copyright (C) 2023 Siriling <siriling@qq.com>
# This is free software, licensed under the GNU General Public License v3.

include $(TOPDIR)/rules.mk


PKG_NAME:=luci-app-secondsystem
LUCI_TITLE:=Luci Secondsystem Support for Nradio660
LUCI_PKGARCH:=all
PKG_VERSION:=1.0.0
LUCI_DEPENDS:=+luci
		

include $(TOPDIR)/feeds/luci/luci.mk

